[package]
name = "pimesh-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
ratatui = "0.27.0"
rusqlite = { version = "0.32.0", features = ["bundled"] }
